### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by spooner01** [skiphs/AMIDST#103]
Every time I try to create a new map, I get this crash report. I'm using this seed number: 2382787242612878

I get the same problem whether I use the Mac version or the Linux version.

I've pasted the entire crash report right here:
================================
[info] Searching for biome color profiles.
[info] Unable to find biome color profile folder.
[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] Successfully loaded version list. URL: https://s3.amazonaws.com/Minecraft.Download/versions/versions.json
[info] Reading minecraft.jar...
[info] Jar load complete.
[info] Searching for classes...
[debug] Found: [ByteClass aii] as WorldType | CCStringMatch
[debug] Found: [ByteClass ayo] as GenLayer | CCLongMatch
[debug] Found: [ByteClass aym] as IntCache | CCStringMatch
[debug] Found: [ByteClass caf$1] as WorldType | CCRequire
[debug] Found: [ByteClass caf$1] as GenLayer | CCRequire
[debug] Found: [ByteClass caf$1] as IntCache | CCRequire
[info] Class search complete.
[info] Generating version ID...
[info] Loading libraries.
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/com/mojang/netty/1.6/netty-1.6.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/com/google/guava/guava/17.0/guava-17.0.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/com/mojang/authlib/1.5.22/authlib-1.5.22.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/com/mojang/realms/1.9.8/realms-1.9.8.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/it/unimi/dsi/fastutil/7.0.12_mojang/fastutil-7.0.12_mojang.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
[info] Skipping library: org.lwjgl.lwjgl:lwjgl:2.9.4-nightly-20150209
[info] Skipping library: org.lwjgl.lwjgl:lwjgl_util:2.9.4-nightly-20150209
[info] Skipping library: org.lwjgl.lwjgl:lwjgl-platform:2.9.4-nightly-20150209
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.2-nightly-20140822/lwjgl-2.9.2-nightly-20140822.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.2-nightly-20140822/lwjgl_util-2.9.2-nightly-20140822.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822-natives-osx.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar
[info] Loading libraries.
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/com/mojang/netty/1.6/netty-1.6.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/com/google/guava/guava/17.0/guava-17.0.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/com/mojang/authlib/1.5.22/authlib-1.5.22.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/com/mojang/realms/1.9.8/realms-1.9.8.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/it/unimi/dsi/fastutil/7.0.12_mojang/fastutil-7.0.12_mojang.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
[info] Skipping library: org.lwjgl.lwjgl:lwjgl:2.9.4-nightly-20150209
[info] Skipping library: org.lwjgl.lwjgl:lwjgl_util:2.9.4-nightly-20150209
[info] Skipping library: org.lwjgl.lwjgl:lwjgl-platform:2.9.4-nightly-20150209
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.2-nightly-20140822/lwjgl-2.9.2-nightly-20140822.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.2-nightly-20140822/lwjgl_util-2.9.2-nightly-20140822.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822-natives-osx.jar
[info] Found library: /Users/Danny/Library/Application Support/minecraft/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar
[info] Identified Minecraft [unknown] with versionID of rboqmdkcpd[Lls;mp[J[[Jml
[info] Loading classes...
[warning] java.lang.NoSuchMethodException: ayo.a(long, aii) Unable to find class method (GenLayer / ayo) (initializeAllBiomeGenerators / a)
[info] Classes loaded.
[info] Minecraft load complete.
[debug] Attempting to create world with seed: 2382787242612878, type: default, and the following generator options:
[debug] 
[crash] Amidst has encounted an uncaught exception on thread: Thread[AWT-EventQueue-0,6,main]
[crash] java.lang.NullPointerException
	at amidst.minecraft.LocalMinecraftInterface.createWorld(LocalMinecraftInterface.java:49)
	at amidst.minecraft.MinecraftUtil.createWorld(MinecraftUtil.java:62)
	at MoF.Project.<init>(Project.java:109)
	at MoF.Project.<init>(Project.java:57)
	at MoF.Project.<init>(Project.java:51)
	at amidst.gui.menu.AmidstMenu$FileMenu$SeedMenuItem$1.actionPerformed(AmidstMenu.java:190)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by stefandollase** [comment]
This repository is no longer maintained. You can find the new repository [here](https://github.com/toolbox4minecraft/amidst).

Please download the latest version of Amidst from https://github.com/toolbox4minecraft/amidst/releases
