### ISSUE TITLE
AMIDST encountered an unexpected error

### ISSUE THREAD

**Issue by ScaRanger** [skiphs/AMIDST#14]
when i try to open a map or load a seed this message shows up

[info] Searching for biome color profiles.
[info] Unable to find biome color profile folder.
[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] Successfully loaded version list. URL: https://s3.amazonaws.com/Minecraft.Download/versions/versions.json
[info] Reading minecraft.jar...
[info] Jar load complete.
[info] Searching for classes...
[debug] Found: [ByteClass awc] as IntCache | CCWildcardByteSearch
[debug] Found: [ByteClass agd] as WorldType | CCStringMatch
[debug] Found: [ByteClass awe] as GenLayer | CCLongMatch
[debug] Found: [ByteClass azd] as WorldType | CCRequire
[debug] Found: [ByteClass azd] as GenLayer | CCRequire
[debug] Found: [ByteClass azd] as IntCache | CCRequire
[info] Class search complete.
[info] Generating version ID...
[info] Loading libraries.
[info] Found library: C:\Users\ScaRanger\AppData\Roaming.minecraft\libraries\java3d\vecmath\1.3.1\vecmath-1.3.1.jar
[info] Found library: C:\Users\ScaRanger\AppData\Roaming.minecraft\libraries\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar
[info] Found library: C:\Users\ScaRanger\AppData\Roaming.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar
[info] Found library: C:\Users\ScaRanger\AppData\Roaming.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.5\jopt-simple-4.5.jar
[info] Found library: C:\Users\ScaRanger\AppData\Roaming.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar
[info] Found library: C:\Users\ScaRanger\AppData\Roaming.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar
[info] Found library: C:\Users\ScaRanger\AppData\Roaming.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar
[info] Found library: C:\Users\ScaRanger\AppData\Roaming.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar
[info] Found library: C:\Users\ScaRanger\AppData\Roaming.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar
[info] Found library: C:\Users\ScaRanger\AppData\Roaming.minecraft\libraries\io\netty\netty-all\4.0.10.Final\netty-all-4.0.10.Final.jar
[info] Found library: C:\Users\ScaRanger\AppData\Roaming.minecraft\libraries\com\google\guava\guava\15.0\guava-15.0.jar
[info] Found library: C:\Users\ScaRanger\AppData\Roaming.minecraft\libraries\org\apache\commons\commons-lang3\3.1\commons-lang3-3.1.jar
[info] Found library: C:\Users\ScaRanger\AppData\Roaming.minecraft\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar
[info] Found library: C:\Users\ScaRanger\AppData\Roaming.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar
[info] Found library: C:\Users\ScaRanger\AppData\Roaming.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar
[info] Found library: C:\Users\ScaRanger\AppData\Roaming.minecraft\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar
[info] Found library: C:\Users\ScaRanger\AppData\Roaming.minecraft\libraries\com\mojang\authlib\1.2\authlib-1.2.jar
[info] Found library: C:\Users\ScaRanger\AppData\Roaming.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar
[info] Found library: C:\Users\ScaRanger\AppData\Roaming.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar
[info] Found library: C:\Users\ScaRanger\AppData\Roaming.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.1-nightly-20131120\lwjgl-2.9.1-nightly-20131120.jar
[info] Found library: C:\Users\ScaRanger\AppData\Roaming.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.1-nightly-20131120\lwjgl_util-2.9.1-nightly-20131120.jar
[info] Found library: C:\Users\ScaRanger\AppData\Roaming.minecraft\libraries\org\lwjgl\lwjgl\lwjgl-platform\2.9.1-nightly-20131120\lwjgl-platform-2.9.1-nightly-20131120-natives-windows.jar
[info] Found library: C:\Users\ScaRanger\AppData\Roaming.minecraft\libraries\net\java\jinput\jinput-platform\2.0.5\jinput-platform-2.0.5-natives-windows.jar
[info] Found library: C:\Users\ScaRanger\AppData\Roaming.minecraft\libraries\tv\twitch\twitch\5.12\twitch-5.12.jar
[info] Found library: C:\Users\ScaRanger\AppData\Roaming.minecraft\libraries\tv\twitch\twitch-platform\5.12\twitch-platform-5.12-natives-windows-32.jar
[info] Found library: C:\Users\ScaRanger\AppData\Roaming.minecraft\libraries\tv\twitch\twitch-external-platform\4.5\twitch-external-platform-4.5-natives-windows-32.jar
[info] Identified Minecraft [V1_7_4] with versionID of pzozmvjs[Lmm;lg[J[[J
[info] Loading classes...
[info] Classes loaded.
[info] Minecraft load complete.
[info] Multiplayer map detected.
[crash] Amidst has encounted an uncaught exception on thread: Thread[AWT-EventQueue-0,6,main]
[crash] java.lang.ExceptionInInitializerError
    at amidst.map.MapObjectPlayer.<init>(MapObjectPlayer.java:18)
    at MoF.SaveLoader.addPlayer(SaveLoader.java:202)
    at MoF.SaveLoader.<init>(SaveLoader.java:187)
    at amidst.gui.menu.AmidstMenu$FileMenu$FileMenuItem$1.actionPerformed(AmidstMenu.java:248)
    at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
    at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
    at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
    at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
    at javax.swing.AbstractButton.doClick(Unknown Source)
    at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
    at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
    at java.awt.Component.processMouseEvent(Unknown Source)
    at javax.swing.JComponent.processMouseEvent(Unknown Source)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$200(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: input == null!
    at javax.imageio.ImageIO.read(Unknown Source)
    at amidst.resources.ResourceLoader.getImage(ResourceLoader.java:24)
    at amidst.map.MapMarkers.<init>(MapMarkers.java:26)
    at amidst.map.MapMarkers.<clinit>(MapMarkers.java:15)
    ... 42 more

**Comment by che-midas** [comment]
I am getting the same thing.  I am on Minecraft 1.9.2, but it was happening with 1.9 as well.  Setup: Windows 10 64bit with java version "1.8.0_73" - Java(TM) SE Runtime Environment (build 1.8.0_73-b02).
