### ISSUE TITLE
An uncaught exception on thread: Thread[AWT-EventQueue-0,6,main]

### ISSUE THREAD

**Issue by CYON4D** [skiphs/AMIDST#50]
I have been trying to get Amidst work on both of my computers with no success. I could never get Amidst to display any map so far.
My home computer is a desktop PC runs windows 7 x86 and it is a pretty good gaming PC.
My office computer is a laptop that runs windows 7 64-bit and it is a i5 with 8gb of ram and a decent graphics card.

I tried Amidst with lots of different minecraft profile versions. All 1.7 version and the latest 1.8 but I always get the same error. I downloaded the latest v1.8 update for Amidst here on github and tried both exe and jar versions on Windows but it still crashes on every single version.

Here is the full error message I am getting:

[info] Searching for biome color profiles.
[info] Unable to find biome color profile folder.
[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] Reading minecraft.jar...
[info] Successfully loaded version list. URL: https://s3.amazonaws.com/Minecraft.Download/versions/versions.json
[info] Jar load complete.
[info] Searching for classes...
[debug] Found: [ByteClass axl] as IntCache | CCWildcardByteSearch
[debug] Found: [ByteClass ahm] as WorldType | CCStringMatch
[debug] Found: [ByteClass axn] as GenLayer | CCLongMatch
[debug] Found: [ByteClass baj] as WorldType | CCRequire
[debug] Found: [ByteClass baj] as GenLayer | CCRequire
[debug] Found: [ByteClass baj] as IntCache | CCRequire
[info] Class search complete.
[info] Generating version ID...
[info] Loading libraries.
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\com\mojang\realms\1.3.5\realms-1.3.5.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\java3d\vecmath\1.3.1\vecmath-1.3.1.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.5\jopt-simple-4.5.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\io\netty\netty-all\4.0.10.Final\netty-all-4.0.10.Final.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\com\google\guava\guava\15.0\guava-15.0.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\org\apache\commons\commons-lang3\3.1\commons-lang3-3.1.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\com\mojang\authlib\1.5.16\authlib-1.5.16.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.1\lwjgl-2.9.1.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.1\lwjgl_util-2.9.1.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\org\lwjgl\lwjgl\lwjgl-platform\2.9.1\lwjgl-platform-2.9.1-natives-windows.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\net\java\jinput\jinput-platform\2.0.5\jinput-platform-2.0.5-natives-windows.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\tv\twitch\twitch\5.16\twitch-5.16.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\tv\twitch\twitch-platform\5.16\twitch-platform-5.16-natives-windows-32.jar
[info] Found library: C:\Users\Cuneyt\AppData\Roaming.minecraft\libraries\tv\twitch\twitch-external-platform\4.5\twitch-external-platform-4.5-natives-windows-32.jar
[info] Identified Minecraft [unknown] with versionID of riqinckb[Lmt;oi[J[[Jns
[info] Loading classes...
[info] Classes loaded.
[info] Minecraft load complete.
[crash] Amidst has encounted an uncaught exception on thread: Thread[AWT-EventQueue-0,6,main]
[crash] java.lang.ExceptionInInitializerError
    at amidst.map.MapObjectStronghold.<init>(MapObjectStronghold.java:7)
    at amidst.map.layers.StrongholdLayer.findStrongholds(StrongholdLayer.java:128)
    at amidst.map.layers.StrongholdLayer.reload(StrongholdLayer.java:148)
    at amidst.map.FragmentManager.setMap(FragmentManager.java:147)
    at amidst.map.Map.<init>(Map.java:49)
    at MoF.MapViewer.<init>(MapViewer.java:123)
    at MoF.Project.<init>(Project.java:113)
    at MoF.Project.<init>(Project.java:61)
    at amidst.gui.menu.AmidstMenu$FileMenu$RandomSeedMenuItem$1.actionPerformed(AmidstMenu.java:223)
    at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
    at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
    at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
    at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
    at javax.swing.AbstractButton.doClick(Unknown Source)
    at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
    at javax.swing.plaf.basic.BasicMenuItemUI$Handler.menuDragMouseReleased(Unknown Source)
    at javax.swing.JMenuItem.fireMenuDragMouseReleased(Unknown Source)
    at javax.swing.JMenuItem.processMenuDragMouseEvent(Unknown Source)
    at javax.swing.JMenuItem.processMouseEvent(Unknown Source)
    at javax.swing.MenuSelectionManager.processMouseEvent(Unknown Source)
    at javax.swing.plaf.basic.BasicPopupMenuUI$MouseGrabber.eventDispatched(Unknown Source)
    at java.awt.Toolkit$SelectiveAWTEventListener.eventDispatched(Unknown Source)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Unknown Source)
    at java.awt.Toolkit.notifyAWTEventListeners(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$400(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: input == null!
    at javax.imageio.ImageIO.read(Unknown Source)
    at amidst.resources.ResourceLoader.getImage(ResourceLoader.java:24)
    at amidst.map.MapMarkers.<init>(MapMarkers.java:26)
    at amidst.map.MapMarkers.<clinit>(MapMarkers.java:15)
    ... 51 more

**Comment by mazarat-tan** [comment]
Having the same issue. Any fix or recommendations?
