### ISSUE TITLE
AMIDST 3.7 Minecraft 1.8.1 Crash on click

### ISSUE THREAD

**Issue by itarchmerc** [skiphs/AMIDST#72]
I am able to open my world in AMIDST just fine.  I can turn layers on and off without issue.  If I try to click on any of the icons in order to get the coordinates, AMIDST crashes.   I am running the following:

minecraft 1.8.1
AMIDST 3.7
Mac OS X 10.10.1
Java 1.8.0.25

This is the error that is generated when clicking:

[warning] java.lang.NoSuchMethodException: boy.a(long, arb) Unable to find class method (GenLayer / boy) (initializeAllBiomeGenerators / a)
[debug] Attempting to create world with seed: 6064296064339504143, type: Default, and the following generator options:
[debug] 
[crash] Amidst has encounted an uncaught exception on thread: Thread[AWT-EventQueue-0,6,main]
[crash] java.lang.NullPointerException
	at MoF.MapViewer.mousePressed(MapViewer.java:295)
	at java.awt.Component.processMouseEvent(Component.java:6522)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4530)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:719)
	at java.awt.EventQueue$4.run(EventQueue.java:717)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by Treer** [comment]
[I might have fixed this in a fork](https://github.com/Treer/AMIDST/commit/aae48db0236834ae3febe843e2ad950b5bf34684) - it's certainly something skiphs could try.

Are you using a normal mouse as the pointing device? Because the bug I fixed occurs when getMousePosition() fails after a click (in my case because the cursor was no longer over the window).

**Comment by itarchmerc** [comment]
Using that fix worked.  I was able to open the map and click the icons to get the coordinates.  Thanks.

**Comment by Treer** [comment]
Good to hear. 

I'm happy for it to be merged in - until now I didn't think it was a fix that mattered much.

If nobody else merges it in I'll get around to it eventually (there's a bunch of other stuff I need to sort through and merge in), though Skiphs will have to be around to accept pull requests.

**Comment by WrightMo** [comment]
I was about to post when I came across this. I too am having the same error, but am using a mouse in this case. I have tried using the trackpad as well to see if the mouse was not registering properly, but have the same end result. This occurs in 1.8.1, 1.8.0, & 1.7.9 (have not tried other versions) running on Mac OSX 10.8.5, Java v8 u25, Amidst v3.7. I have kept the cursor in the window during the full time of loading the map and it stays stable until I try to click on a icon, or move the map. My mouse is a Steel Series Sensei gaming mouse running the latest version of SteelSeries Engine. The trackpad also turns up the same result.
