### ISSUE TITLE
AMIDST has crashed with the following message: Amidst has encounter an uncounted an uncaught exceptions on the thread: Thread[AWT-EventQueue-0,6,main]

### ISSUE THREAD

**Issue by Qianli-Ma** [skiphs/AMIDST#95]
Running minecraft 1.9
`[info] Searching for biome color profiles.
[info] Unable to find biome color profile folder.
[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] Successfully loaded version list. URL: https://s3.amazonaws.com/Minecraft.Download/versions/versions.json
[info] Reading minecraft.jar...
[info] Jar load complete.
[info] Searching for classes...
[debug] Found: [ByteClass ahy] as WorldType | CCStringMatch
[debug] Found: [ByteClass axv] as GenLayer | CCLongMatch
[debug] Found: [ByteClass axt] as IntCache | CCStringMatch
[debug] Found: [ByteClass bzg$1] as WorldType | CCRequire
[debug] Found: [ByteClass bzg$1] as GenLayer | CCRequire
[debug] Found: [ByteClass bzg$1] as IntCache | CCRequire
[info] Class search complete.
[info] Generating version ID...
[info] Loading libraries.
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/com/google/guava/guava/17.0/guava-17.0.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/com/mojang/authlib/1.5.22/authlib-1.5.22.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/com/mojang/realms/1.8.4/realms-1.8.4.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
[info] Skipping library: org.lwjgl.lwjgl:lwjgl:2.9.4-nightly-20150209
[info] Skipping library: org.lwjgl.lwjgl:lwjgl_util:2.9.4-nightly-20150209
[info] Skipping library: org.lwjgl.lwjgl:lwjgl-platform:2.9.4-nightly-20150209
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.2-nightly-20140822/lwjgl-2.9.2-nightly-20140822.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.2-nightly-20140822/lwjgl_util-2.9.2-nightly-20140822.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822-natives-osx.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar
[info] Loading libraries.
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/com/google/guava/guava/17.0/guava-17.0.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/com/mojang/authlib/1.5.22/authlib-1.5.22.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/com/mojang/realms/1.8.4/realms-1.8.4.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
[info] Skipping library: org.lwjgl.lwjgl:lwjgl:2.9.4-nightly-20150209
[info] Skipping library: org.lwjgl.lwjgl:lwjgl_util:2.9.4-nightly-20150209
[info] Skipping library: org.lwjgl.lwjgl:lwjgl-platform:2.9.4-nightly-20150209
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.2-nightly-20140822/lwjgl-2.9.2-nightly-20140822.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.2-nightly-20140822/lwjgl_util-2.9.2-nightly-20140822.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822-natives-osx.jar
[info] Found library: /Users/QianliMa-MAC/Library/Application Support/minecraft/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar
[info] Identified Minecraft [unknown] with versionID of qwoomajzpb[Llp;mm[J[[Jmi
[info] Loading classes...
[warning] java.lang.NoSuchMethodException: axv.a(long, ahy) Unable to find class method (GenLayer / axv) (initializeAllBiomeGenerators / a)
[info] Classes loaded.
[info] Minecraft load complete.
[debug] Attempting to create world with seed: 4877795449116332292, type: default, and the following generator options:
[debug] 
[crash] Amidst has encounted an uncaught exception on thread: Thread[AWT-EventQueue-0,6,main]
[crash] java.lang.NullPointerException
    at amidst.minecraft.LocalMinecraftInterface.createWorld(LocalMinecraftInterface.java:49)
    at amidst.minecraft.MinecraftUtil.createWorld(MinecraftUtil.java:62)
    at MoF.Project.<init>(Project.java:109)
    at MoF.Project.<init>(Project.java:57)
    at MoF.Project.<init>(Project.java:51)
    at amidst.gui.menu.AmidstMenu$FileMenu$SeedMenuItem$1.actionPerformed(AmidstMenu.java:190)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2028)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2351)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:242)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:389)
    at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:95)
    at java.awt.MenuItem.processActionEvent(MenuItem.java:650)
    at java.awt.MenuItem.processEvent(MenuItem.java:609)
    at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:343)
    at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:331)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:720)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:690)
    at java.awt.EventQueue$3.run(EventQueue.java:688)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:687)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

`

**Comment by stefandollase** [comment]
Please download the current version of Amidst and try again:
https://github.com/toolbox4minecraft/amidst/releases

**Comment by alexmufatti** [comment]
Same problem here using the last beta version.

**Comment by stefandollase** [comment]
@alexmufatti
You are probably facing the same issue as most of the other users, see toolbox4minecraft/amidst#247.

**Comment by alexmufatti** [comment]
Thank you @stefandollase
